### ISSUE TITLE
Marking remover 

### ISSUE THREAD

**Issue by Bellwar** [MacSergey/NodeMarkup#225]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
Roads and lines.

#### Describe your idea clearly and concisely.  
I like the idea of making my own crosswalk but with no way to remove the one already there, it doesn't have a point.

Also with the addition of the ability to change segments, this is now needed for roads too.

I know TM:PE can remove crosswalks but people won't use them afterward. Also, there are mods for that and a mod for turning off all marking on road. But all.... not just segments I want. 

#### Screenshots?  
You can see the lines getting in each other way and not being able to work it to a better extend.
  
![image](https://user-images.githubusercontent.com/9407653/112362089-5c094980-8cd4-11eb-94c3-951ff9e10fee.png)

#### Why would this idea be a good addition to IMT?

I think this would be a nice addition to the roads and crosswalk. If it would be right in the mod it would make it 10x nicer compare to using another 5 mods to make it somewhat work.

**Comment by MacSergey** [comment]
remove only crosswalk marking you can with none controller
https://steamcommunity.com/sharedfiles/filedetails/?id=2085403475

it is not possible to remove the markings from the roads. it is drawn on the road texture and it is impossible to determine what is a marking and what is not

**Comment by Bellwar** [comment]
I closed this since you are right. Maybe just an idea. Creating a double layer or "hider" that would be just above the marking and would cover it with the flat color of your liking? Just make it a flat solid thick line that you can draw over a second new line. Would that be imposible?

**Comment by Bellwar** [comment]
![image](https://user-images.githubusercontent.com/9407653/112365593-20707e80-8cd8-11eb-99a0-ac6e9c312c89.png)

Just tried it in the game. You let me draw a line over line like this.... why not make "bottom cover up line" that would alway render under other lines and you can creat line over underline to make your own. I wouldn't sort everything out but most of the cases yes. Just idea for you

**Comment by MacSergey** [comment]
this way is not performance friendly

**Comment by Bellwar** [comment]
Well put a note there and let people now. Just let me draw two lines over each other. You don't have to give me more.

But it is your mod and you decide. Don't take this as me being rude. I love the mod and the whole work around it and I thank you a lot for what you did. Either way, you decide.

**Comment by phillycheeze** [comment]
For anyone else stumbling upon this issue, to remove existing lines I often just create a solid color line (Alpha set to 255) that is a very close match to the pavement color. That has worked for me to remove existing markings on road assets. Another way is to create a filler covering the entire road to be a static, pavement-like color - but this looks less realistic since the road textures have finer details that are lost this way.

It would be nice if the mod had the ability to create two lines over the same two points. That way we can remove existing line textures with the hack above, and then create a second line with our desired markings on top of it. Alternatively, maybe adding an option for dashed-based lines to have a background-color (setting the color where the "spaces" exist).

Regardless, love the mod and appreciate the hard work! I'm more than happy to take a crack at a PR request if it's viable.
